# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sankalp Jain\Downloads\Telegram Desktop\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QSize
import os
import threading


rubbishExt = ['.tmp', '.bak', '.prv', '.old', '.wbk', '.err', '.xlk', '_mp', '.gid', '.chk', '.syd', '.$$$', '.@@@',
              ".~*"]
filext = ['.txt', '.pdf', '.docx']


def GetDrives():
    drives = []
    for i in range(65, 91):
        vol = chr(i) + ":/"
        if os.path.isdir(vol):
            drives.append(vol)
    return tuple(drives)


class Ui_MainWindow(object):
    def __init__(self):
        self.file_index = []
        self.record = 0
        self.searchl = []
        self.index2 = []
        self.l = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 502)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("*{\n"
                                 "    border:none;\n"
                                 "    background-color:transparent;\n"
                                 "    background:transparent;\n"
                                 "    padding:0;\n"
                                 "    margin:0;\n"
                                 "    color:#fff;\n"
                                 "}\n"
                                 "#centralwidget{\n"
                                 "    background-color: #16191d;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 40, 611, 431))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomeWindow = QtWidgets.QWidget()
        self.HomeWindow.setObjectName("HomeWindow")
        self.RefreshButton = QtWidgets.QPushButton(self.HomeWindow)
        self.RefreshButton.setGeometry(QtCore.QRect(190, 70, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.RefreshButton.setFont(font)
        self.RefreshButton.setAutoFillBackground(False)
        self.RefreshButton.setStyleSheet("border-width: 3px;\n"
                                         "border-style: outset;\n"
                                         "border-color: black;\n"
                                         "border-radius: 20px;\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "background-color:#1f232a;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/refresh-ccw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RefreshButton.setIcon(icon)
        self.RefreshButton.setIconSize(QtCore.QSize(30, 30))
        self.RefreshButton.setObjectName("RefreshButton")
        self.CleanButton = QtWidgets.QPushButton(self.HomeWindow)
        self.CleanButton.setGeometry(QtCore.QRect(190, 170, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CleanButton.setFont(font)
        self.CleanButton.setStyleSheet("border-width: 3px;\n"
                                       "border-style: outset;\n"
                                       "border-color: black;\n"
                                       "border-radius: 20px;\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "background-color:#1f232a;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/trash-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CleanButton.setIcon(icon1)
        self.CleanButton.setIconSize(QtCore.QSize(30, 30))
        self.CleanButton.setObjectName("CleanButton")
        self.SearchButton = QtWidgets.QPushButton(self.HomeWindow)
        self.SearchButton.setGeometry(QtCore.QRect(190, 270, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet("border-width: 3px;\n"
                                        "border-style: outset;\n"
                                        "border-color: black;\n"
                                        "border-radius: 20px;\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color:#1f232a;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon2)
        self.SearchButton.setIconSize(QtCore.QSize(30, 30))
        self.SearchButton.setObjectName("SearchButton")
        self.label = QtWidgets.QLabel(self.HomeWindow)
        self.label.setGeometry(QtCore.QRect(80, 40, 481, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.HomeWindow)
        self.RefreshWindow = QtWidgets.QWidget()
        self.RefreshWindow.setStyleSheet("")
        self.RefreshWindow.setObjectName("RefreshWindow")
        self.scroll = QtWidgets.QScrollArea(self.RefreshWindow)  # Scroll Area which contains the widgets, set as the centralWidget
        self.widget = QtWidgets.QWidget()  # Widget that contains the collection of Vertical Box
        self.vbox = QtWidgets.QVBoxLayout()
        self.stackedWidget.addWidget(self.RefreshWindow)
        self.CleanWindow = QtWidgets.QWidget()
        self.CleanWindow.setObjectName("CleanWindow")
        self.drives = GetDrives()
        t = threading.Thread(target=self.ScanRubbish, args=(self.drives,))
        t.start()
        self.scrollArea = QtWidgets.QScrollArea(self.CleanWindow)
        self.scrollArea.setGeometry(QtCore.QRect(20, 10, 591, 321))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setStyleSheet("border-width: 5px;\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color:#1f232a;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.b = QtWidgets.QPlainTextEdit(self.scrollArea)
        self.b.resize(574, 321)
        self.selectallButton = QtWidgets.QPushButton(self.CleanWindow)
        self.selectallButton.setGeometry(QtCore.QRect(420, 390, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selectallButton.setFont(font)
        self.selectallButton.setStyleSheet("border-width: 3px;\n"
                                           "border-style: outset;\n"
                                           "border-color: black;\n"
                                           "border-radius: 20px;\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "background-color:#1f232a;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectallButton.setIcon(icon3)
        self.selectallButton.setIconSize(QtCore.QSize(25, 25))
        self.selectallButton.setObjectName("selectallButton")
        self.DeleteButton = QtWidgets.QPushButton(self.CleanWindow)
        self.DeleteButton.setGeometry(QtCore.QRect(100, 390, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setStyleSheet("border-width: 3px;\n"
                                        "border-style: outset;\n"
                                        "border-color: black;\n"
                                        "border-radius: 20px;\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color:#1f232a;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteButton.setIcon(icon4)
        self.DeleteButton.setIconSize(QtCore.QSize(25, 25))
        self.DeleteButton.setObjectName("DeleteButton")
        self.notificationclean = QtWidgets.QTextEdit(self.CleanWindow)
        self.notificationclean.setGeometry(QtCore.QRect(50, 340, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.notificationclean.setFont(font)
        self.notificationclean.setStyleSheet("border-width: 2px;\n"
                                             "border-style: outset;\n"
                                             "border-color: black;\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "background-color:#1f232a;\n"
                                             "")
        self.notificationclean.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notificationclean.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notificationclean.setObjectName("notificationclean")
        self.stackedWidget.addWidget(self.CleanWindow)
        self.SearchTypeWindow = QtWidgets.QWidget()
        self.SearchTypeWindow.setObjectName("SearchTypeWindow")
        self.searchindevButton = QtWidgets.QPushButton(self.SearchTypeWindow)
        self.searchindevButton.setGeometry(QtCore.QRect(210, 60, 201, 91))
        self.searchindevButton.setStyleSheet("border-width: 3px;\n"
                                             "border-style: outset;\n"
                                             "border-color: black;\n"
                                             "border-radius: 30px;\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "background-color:#1f232a;\n"
                                             "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/monitor.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchindevButton.setIcon(icon5)
        self.searchindevButton.setIconSize(QtCore.QSize(35, 35))
        self.searchindevButton.setObjectName("searchindevButton")
        self.searchindocButton = QtWidgets.QPushButton(self.SearchTypeWindow)
        self.searchindocButton.setGeometry(QtCore.QRect(210, 230, 201, 91))
        self.searchindocButton.setStyleSheet("border-width: 3px;\n"
                                             "border-style: outset;\n"
                                             "border-color: black;\n"
                                             "border-radius: 30px;\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "background-color:#1f232a;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchindocButton.setIcon(icon6)
        self.searchindocButton.setIconSize(QtCore.QSize(35, 35))
        self.searchindocButton.setObjectName("searchindocButton")
        self.stackedWidget.addWidget(self.SearchTypeWindow)
        self.SearchinDevWindow = QtWidgets.QWidget()
        self.SearchinDevWindow.setObjectName("SearchinDevWindow")
        self.comboBox = QtWidgets.QComboBox(self.SearchinDevWindow)
        self.comboBox.setGeometry(QtCore.QRect(280, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border-width: 2px;\n"
                                    "border-style: outset;\n"
                                    "border-color: black;\n"
                                    "border-radius: 5px;\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "background-color:#1f232a;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.keywordtext = QtWidgets.QTextEdit(self.SearchinDevWindow)
        self.keywordtext.setGeometry(QtCore.QRect(20, 20, 221, 31))
        self.keywordtext.setStyleSheet("border-width: 2px;\n"
                                       "border-style: outset;\n"
                                       "border-color: black;\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "background-color:#1f232a;")
        self.keywordtext.setObjectName("keywordtext")
        self.searchdevButton_2 = QtWidgets.QPushButton(self.SearchinDevWindow)
        self.searchdevButton_2.setGeometry(QtCore.QRect(380, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.searchdevButton_2.setFont(font)
        self.searchdevButton_2.setStyleSheet("border-width: 2px;\n"
                                             "border-style: outset;\n"
                                             "border-color: black;\n"
                                             "border-radius: 10px;\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "background-color:#1f232a;")
        self.searchdevButton_2.setIcon(icon2)
        self.searchdevButton_2.setObjectName("searchdevButton_2")
        #self.searchdevButton_2.clicked.connect(self.on_click)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.SearchinDevWindow)
        self.scrollArea_3.setGeometry(QtCore.QRect(20, 70, 581, 321))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scrollArea_3.setFont(font)
        self.scrollArea_3.setAutoFillBackground(True)
        self.scrollArea_3.setStyleSheet("border-width: 5px;\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color:#1f232a;")
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 564, 321))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.previewdevButton = QtWidgets.QPushButton(self.SearchinDevWindow)
        self.previewdevButton.setGeometry(QtCore.QRect(510, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.previewdevButton.setFont(font)
        self.previewdevButton.setStyleSheet("border-width: 2px;\n"
                                            "border-style: outset;\n"
                                            "border-color: black;\n"
                                            "border-radius: 10px;\n"
                                            "color: rgb(255, 255, 255);\n"
                                            "background-color:#1f232a;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/clipboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previewdevButton.setIcon(icon7)
        self.previewdevButton.setObjectName("previewdevButton")
        self.notificationtext = QtWidgets.QTextEdit(self.SearchinDevWindow)
        self.notificationtext.setGeometry(QtCore.QRect(40, 400, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.notificationtext.setFont(font)
        self.notificationtext.setStyleSheet("border-width: 2px;\n"
                                            "border-style: outset;\n"
                                            "border-color: black;\n"
                                            "color: rgb(255, 255, 255);\n"
                                            "background-color:#1f232a;")
        self.notificationtext.setObjectName("notificationtext")
        self.stackedWidget.addWidget(self.SearchinDevWindow)
        self.SearchinDocWindow = QtWidgets.QWidget()
        self.SearchinDocWindow.setObjectName("SearchinDocWindow")
        self.previewdocButton = QtWidgets.QPushButton(self.SearchinDocWindow)
        self.previewdocButton.setGeometry(QtCore.QRect(490, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.previewdocButton.setFont(font)
        self.previewdocButton.setStyleSheet("border-width: 2px;\n"
                                            "border-style: outset;\n"
                                            "border-color: black;\n"
                                            "border-radius: 10px;\n"
                                            "color: rgb(255, 255, 255);\n"
                                            "background-color:#1f232a;")
        self.previewdocButton.setIcon(icon7)
        self.previewdocButton.setIconSize(QtCore.QSize(25, 25))
        self.previewdocButton.setObjectName("previewdocButton")
        self.searchdevButton = QtWidgets.QPushButton(self.SearchinDocWindow)
        self.searchdevButton.setGeometry(QtCore.QRect(320, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.searchdevButton.setFont(font)
        self.searchdevButton.setStyleSheet("border-width: 2px;\n"
                                           "border-style: outset;\n"
                                           "border-color: black;\n"
                                           "border-radius: 10px;\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "background-color:#1f232a;")
        self.searchdevButton.setIcon(icon2)
        self.searchdevButton.setIconSize(QtCore.QSize(25, 25))
        self.searchdevButton.setObjectName("searchdevButton")
        self.keyworddoctext = QtWidgets.QLineEdit(self.SearchinDocWindow)
        self.keyworddoctext.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.keyworddoctext.setStyleSheet("border-width: 2px;\n"
                                          "border-style: outset;\n"
                                          "border-color: black;\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "background-color:#1f232a;")
        self.keyworddoctext.setObjectName("keyworddoctext")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.SearchinDocWindow)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 70, 601, 351))
        self.scrollArea_2.setStyleSheet("border-width: 5px;\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color:#1f232a;")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 584, 351))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.SearchinDocWindow)
        self.AboutWindow = QtWidgets.QWidget()
        self.AboutWindow.setStyleSheet("background-image: url(:/newPrefix/datasight_logo-removebg-preview.png);")
        self.AboutWindow.setObjectName("AboutWindow")
        self.label_2 = QtWidgets.QLabel(self.AboutWindow)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 340, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.AboutWindow)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.AboutWindow)
        self.label_4.setGeometry(QtCore.QRect(360, 380, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.AboutWindow)
        self.FAQWindow = QtWidgets.QWidget()
        self.FAQWindow.setObjectName("FAQWindow")
        self.stackedWidget.addWidget(self.FAQWindow)
        self.HomeButton = QtWidgets.QPushButton(self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HomeButton.setFont(font)
        self.HomeButton.setStyleSheet("border-width: 2px;\n"
                                      "border-style: outset;\n"
                                      "border-color: black;\n"
                                      "border-radius: 10px;\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color:#1f232a;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeButton.setIcon(icon8)
        self.HomeButton.setObjectName("HomeButton")
        self.AboutButton = QtWidgets.QPushButton(self.centralwidget)
        self.AboutButton.setGeometry(QtCore.QRect(90, 10, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.AboutButton.setFont(font)
        self.AboutButton.setStyleSheet("border-width: 2px;\n"
                                       "border-style: outset;\n"
                                       "border-color: black;\n"
                                       "border-radius: 10px;\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "background-color:#1f232a;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AboutButton.setIcon(icon9)
        self.AboutButton.setObjectName("AboutButton")
        self.FAQButton = QtWidgets.QPushButton(self.centralwidget)
        self.FAQButton.setGeometry(QtCore.QRect(170, 10, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.FAQButton.setFont(font)
        self.FAQButton.setStyleSheet("border-width: 2px;\n"
                                     "border-style: outset;\n"
                                     "border-color: black;\n"
                                     "border-radius: 10px;\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "background-color:#1f232a;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/loader.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FAQButton.setIcon(icon10)
        self.FAQButton.setObjectName("FAQButton")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(250, 10, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("border-width: 2px;\n"
                                      "border-style: outset;\n"
                                      "border-color: black;\n"
                                      "border-radius: 10px;\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color:#1f232a;")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons/external-link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitButton.setIcon(icon11)
        self.ExitButton.setObjectName("ExitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionFAQ = QtWidgets.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def on(self):
        print("prasuk")

    def on_click(self):
        textboxValue = self.textbox.text()
        QtWidgets.QMessageBox.question(self, 'Message - pythonspot.com', "You typed: " + textboxValue,
                                       QtWidgets.QMessageBox.Ok,
                                       QtWidgets.QMessageBox.Ok)
        self.textbox.setText("")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.CleanButton.setText(_translate("MainWindow", "Clean"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(
            _translate("MainWindow", "*Note    After Starting the Application, please click on the Refresh Button"))
        self.selectallButton.setText(_translate("MainWindow", "Delete"))
        self.DeleteButton.setText(_translate("MainWindow", "Select All"))
        self.searchindevButton.setText(_translate("MainWindow", "Search In Device"))
        self.searchindocButton.setText(_translate("MainWindow", "Search In Document"))
        self.comboBox.setItemText(0, _translate("MainWindow", ".pdf"))
        self.comboBox.setItemText(1, _translate("MainWindow", ".docx"))
        self.comboBox.setItemText(2, _translate("MainWindow", ".odt"))
        self.comboBox.setItemText(3, _translate("MainWindow", ".rtf"))
        self.searchdevButton_2.setText(_translate("MainWindow", "Search"))
        self.previewdevButton.setText(_translate("MainWindow", "Preview"))
        self.previewdocButton.setText(_translate("MainWindow", "Preview"))
        self.searchdevButton.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Made By : Prasuk Jain, Aman Jain, Ritik Jain, Sankalp Jain"))
        self.label_3.setText(_translate("MainWindow", "A File Searching And Cleaning Tool"))
        self.label_4.setText(_translate("MainWindow", "Final Year B. Tech. CSE-A"))
        self.HomeButton.setText(_translate("MainWindow", "Home"))
        self.AboutButton.setText(_translate("MainWindow", "About"))
        self.FAQButton.setText(_translate("MainWindow", "FAQ"))
        self.ExitButton.setText(_translate("MainWindow", "Exit"))


import img

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
